// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhYNMF7PkbZk60FD-mHzQOl9BCMChWNo',
    appId: '1:241461826546:web:6abb076a201b972845516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    authDomain: 'leasure-nft-88aaf.firebaseapp.com',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    measurementId: 'G-D4M1PC1KJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLr51tHYecaRibUtw1fsUNb9U3uZQR7Xg',
    appId: '1:241461826546:android:3ddfbba77b70059045516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkNewwIKujQTx3FXQ1A51mRX5JG6UX68',
    appId: '1:241461826546:ios:05623d890756f9e345516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    iosBundleId: 'com.example.leasureNft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnkNewwIKujQTx3FXQ1A51mRX5JG6UX68',
    appId: '1:241461826546:ios:05623d890756f9e345516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    iosBundleId: 'com.example.leasureNft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWhYNMF7PkbZk60FD-mHzQOl9BCMChWNo',
    appId: '1:241461826546:web:fec2d81e40996b9945516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    authDomain: 'leasure-nft-88aaf.firebaseapp.com',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    measurementId: 'G-8CZN2D0QZH',
  );
}
